"""Fetch the template typefaces and write apps/web/app/fonts.css.

Every dashboard template names its own face so the catalogue does not render
as forty copies of one theme (CLAUDE.md, rule 6). Those faces used to come
from a fonts.googleapis.com stylesheet, which meant the page fell back to the
system sans whenever that request was slow or blocked — including in the
headless captures the fidelity audit measures, so every type width compared
against a reference was wrong without anything looking broken.

Self-hosting removes that: the same OFL/Apache-licensed files are served from
apps/web/public/fonts and declared in one generated stylesheet.

Usage:
    python3 scripts/fetch-fonts.py

Re-run it after adding a face to tokens.tsx. The output file is generated;
edit this script rather than the CSS.
"""
from __future__ import annotations

import pathlib
import re
import subprocess

# Google's css2 endpoint varies its payload by user agent. Asking as a current
# browser gets the variable woff2 rather than the legacy static TrueType set,
# which is one file per family instead of five.
UA = (
    "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) "
    "Chrome/126.0.0.0 Safari/537.36"
)

# Keyed by the family name a token set asks for; the value is the css2 spec,
# whose weight range has to cover every weight the templates use.
FAMILIES = {
    "Inter": "Inter:wght@400..700",
    "Inter Tight": "Inter+Tight:wght@400..700",
    "Figtree": "Figtree:wght@400..800",
    "Archivo": "Archivo:wght@400..700",
    "Space Grotesk": "Space+Grotesk:wght@400..700",
    "Plus Jakarta Sans": "Plus+Jakarta+Sans:wght@400..800",
    "DM Sans": "DM+Sans:opsz,wght@9..40,400..700",
    "Manrope": "Manrope:wght@400..800",
    "IBM Plex Sans": "IBM+Plex+Sans:wght@400;500;600;700",
    "Schibsted Grotesk": "Schibsted+Grotesk:wght@400..700",
}

ROOT = pathlib.Path(__file__).resolve().parent.parent
OUT_DIR = ROOT / "apps/web/public/fonts"
OUT_CSS = ROOT / "apps/web/app/fonts.css"

HEADER = """/*
 * The template typefaces, served from this app rather than from Google.
 *
 * Every dashboard template picks its own face to match its reference (see
 * CLAUDE.md), so the catalogue depends on all of them being present. Loading
 * them from fonts.googleapis.com meant the page rendered in a fallback
 * whenever that request was slow or blocked — including in the headless
 * captures the fidelity audit compares against the references, which made
 * every measured type width wrong. These are the same OFL/Apache-licensed
 * files, self-hosted, so the render is the same everywhere.
 *
 * Generated by scripts/fetch-fonts.py; edit that, not this.
 */
"""


def curl(url: str, *, binary_to: pathlib.Path | None = None) -> str:
    args = ["curl", "-sS", "--fail", "-A", UA, url]
    if binary_to is not None:
        args += ["-o", str(binary_to)]
        subprocess.run(args, check=True)
        return ""
    return subprocess.run(args, capture_output=True, text=True, check=True).stdout


def main() -> int:
    OUT_DIR.mkdir(parents=True, exist_ok=True)
    rules: list[str] = []

    for name, spec in FAMILIES.items():
        css = curl(f"https://fonts.googleapis.com/css2?family={spec}&display=swap")
        blocks = re.findall(
            r"/\*\s*([\w\-\[\]]+)\s*\*/\s*(@font-face\s*\{.*?\})", css, re.S
        )
        # These are latin-script product UIs, so the latin subset is the whole
        # need; keeping only it holds the payload near half a megabyte.
        picked = [b for tag, b in blocks if tag == "latin"] or [b for _, b in blocks]
        slug = name.lower().replace(" ", "-")

        for i, block in enumerate(picked):
            src = re.search(r"url\((https://[^)]+\.woff2)\)", block)
            if not src:
                continue
            filename = f"{slug}{'' if i == 0 else f'-{i}'}.woff2"
            curl(src.group(1), binary_to=OUT_DIR / filename)
            block = block.replace(src.group(1), f"/fonts/{filename}")
            rules.append(re.sub(r"^\s+", "  ", block, flags=re.M).strip())

        print(f"{name:20} {len(picked)} face(s)")

    OUT_CSS.write_text(HEADER + "\n" + "\n\n".join(rules) + "\n")
    print(f"wrote {OUT_CSS.relative_to(ROOT)} ({len(rules)} @font-face rules)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
